"""Alter User

Revision ID: f6949367b9ed
Revises: 3b4d6d0904aa
Create Date: 2024-10-01 00:35:40.873989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6949367b9ed'
down_revision: Union[str, None] = '3b4d6d0904aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('user', sa.Column('access_token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('refresh_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'refresh_token')
    op.drop_column('user', 'access_token')
    op.drop_column('user', 'avatar_url')
    # ### end Alembic commands ###
