version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DB_STRING}
  db:
    image: postgres:13
    container_name: ${DB_NAME}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data: